version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tenders
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"


